<a href="https://colab.research.google.com/github/rallm/IUST-DL-Fall2025/blob/main/HW1/ans/hw1_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# definition of X
X = np.array([[1, 10, 5, 3],
              [1, 13, 6, 5],
              [1, 8, 4, 3],
              [1, 16, 9, 4],
              [1, 7, 3, 2]])
X

array([[ 1, 10,  5,  3],
       [ 1, 13,  6,  5],
       [ 1,  8,  4,  3],
       [ 1, 16,  9,  4],
       [ 1,  7,  3,  2]])

In [ ]:
XtX = np.dot(X.T, X)
XtX

array([[  5,  54,  27,  17],
       [ 54, 638, 325, 197],
       [ 27, 325, 167,  99],
       [ 17, 197,  99,  63]])

In [ ]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 4.42553191, -1.74468085,  2.24468085,  0.73404255],
       [-1.74468085,  1.55319149, -2.05319149, -1.15957447],
       [ 2.24468085, -2.05319149,  2.80319149,  1.40957447],
       [ 0.73404255, -1.15957447,  1.40957447,  1.2287234 ]])

In [8]:
Y = np.array([40, 48, 32, 56, 28]).reshape(5, 1)
Y

array([[40],
       [48],
       [32],
       [56],
       [28]])

In [9]:
XtY = np.dot(X.T, Y)
XtY

array([[ 204],
       [2372],
       [1204],
       [ 736]])

In [10]:
w = np.dot(XtX_inv, XtY)
w

array([[7.27659574],
       [2.76595745],
       [0.23404255],
       [0.70212766]])

In [12]:
w = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), Y)
w

array([[7.27659574],
       [2.76595745],
       [0.23404255],
       [0.70212766]])

In [13]:
x_new = np.array([1, 11, 6, 4])
x_new

array([ 1, 11,  6,  4])

In [20]:
solution = np.dot(x_new, w)
print(solution[0])

41.91489361701798
