<a href="https://colab.research.google.com/github/rallm/IUST-DL-Fall2025/blob/main/HW5/helper/hw5_p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F

# 1. Define Inputs
x_prev = torch.tensor([[0.8], [-0.5]])  # x_{t-1}
h_prev2 = torch.tensor([[-0.2], [0.4]]) # h_{t-2}

# 2. Define Weights & Biases based on the image provided in question
W_xh = torch.tensor([[0.5, -0.2],
                     [-1.0, 0.9]])
W_hh = torch.tensor([[0.3, 0.1],
                     [-0.4, 0.2]])
b_h = torch.tensor([[0.1],
                    [-0.1]])

W_hy = torch.tensor([[1.5, -0.5],
                     [0.5, 1.0]])
b_y = torch.tensor([[0.0],
                    [0.0]])

In [2]:
# 3. Calculation Step (Forward Pass for t-1)
# Formula: h = tanh(W_hh * h_prev + W_xh * x + b_h)
term1 = torch.matmul(W_hh, h_prev2)
term2 = torch.matmul(W_xh, x_prev)
h_prev_raw = term1 + term2 + b_h
h_prev = torch.tanh(h_prev_raw)  # This is h_{t-1}

# Formula: y = W_hy * h + b_y
y_prev_raw = torch.matmul(W_hy, h_prev)
# Assuming Softmax for classification output
y_prev = F.softmax(y_prev_raw, dim=0)

print("Step 1: Raw Pre-activation (Z):")
print(h_prev_raw)
print("\nStep 2: Hidden State h_(t-1):")
print(h_prev)
print("\nStep 3: Output Logits y_(t-1):")
print(y_prev_raw)

Step 1: Raw Pre-activation (Z):
tensor([[ 0.5800],
        [-1.1900]])

Step 2: Hidden State h_(t-1):
tensor([[ 0.5227],
        [-0.8306]])

Step 3: Output Logits y_(t-1):
tensor([[ 1.1993],
        [-0.5692]])
